# Generated by Django 5.0 on 2023-12-07 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('register_id', models.IntegerField(primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('rollnum', models.IntegerField()),
                ('_class', models.IntegerField()),
                ('parent', models.CharField(max_length=255)),
            ],
        ),
    ]
