# Generated by Django 5.0 on 2023-12-07 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('division', models.CharField(max_length=255)),
                ('class_teacher', models.CharField(max_length=255)),
            ],
        ),
    ]
